# TBI Pipeline Configuration

preprocessing:
  target_spacing: [1.0, 1.0, 1.0]  # mm
  target_shape: [256, 256, 256]
  bias_correction:
    iterations: [50, 50, 30, 20]
    convergence_threshold: 0.001
  intensity_normalization:
    percentile_low: 1.0
    percentile_high: 99.0

segmentation:
  model:
    architecture: "unet"
    in_channels: 1
    out_channels: 8  # 7 lesions + background
    channels: [16, 32, 64, 128, 256]
    strides: [2, 2, 2, 2]
    num_res_units: 2
    dropout: 0.1
  
  lesion_types:
    0: "background"
    1: "intraparenchymal_hemorrhage"
    2: "subdural_hematoma"
    3: "epidural_hematoma"
    4: "subarachnoid_hemorrhage"
    5: "intraventricular_hemorrhage"
    6: "diffuse_axonal_injury"
    7: "contusion"

atlas:
  registration_type: "SyN"
  zones:
    1: "frontal_lobe_left"
    2: "frontal_lobe_right"
    3: "parietal_lobe_left"
    4: "parietal_lobe_right"
    5: "temporal_lobe_left"
    6: "temporal_lobe_right"
    7: "occipital_lobe_left"
    8: "occipital_lobe_right"
    9: "cerebellum"
    10: "brainstem"

training:
  batch_size: 2
  learning_rate: 0.001
  epochs: 100
  validation_split: 0.2
  augmentation:
    random_flip: true
    random_rotate: true
    random_scale: true
    random_intensity: true